spring:
    datasource:
        url: jdbc:mysql://localhost:3306/recipe_db?autoReconnect=true&useSSL=false
        username: root
        password: bothways
        driver-class-name: com.mysql.jdbc.Driver